version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:15.1
    restart: always
    ports:
      - '5432:5432'
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge
